// #include <GL/glut.h>
// #include <glm/glm.hpp>
// #include <glm/gtc/matrix_transform.hpp>
// #include <glm/gtc/type_ptr.hpp>

#include <iostream>
#include <vector>
#include <string>
#include <random>       // Assigning colors

#include "vector.h"
#include "Body.h"
#include "Star.h"
#include "Planet.h"
#include "Moon.h"
#include "BlackHole.h"
#include "FileReader.h"

using namespace std;

int main() {
    // Vector containers for each type of body
    vector<Vector> stars;
    vector<Vector> planets;
    vector<Vector> moons;
    vector<Vector> blackHoles;

    try {
        // Create a FileReader to read the output file generated by the simulation
        FileReader reader("input.txt");
        auto [bodies, stars, planets, moons, blackholes] = reader.readBodies();

        // Output summary of the read data
        cout << "Number of bodies: " << bodies.size() << endl;
        cout << "Number of stars: " << stars.size() << endl;
        cout << "Number of planets: " << planets.size() << endl;
        cout << "Number of moons: " << moons.size() << endl;
        cout << "Number of black holes: " << blackholes.size() << endl;

    } catch (const std::exception& e) {
        cerr << "Error: " << e.what() << endl;
    }

    return 0;
}
